theme = "onedark"

[editor]
bufferline = "multiple"
color-modes = true
cursorline = true
line-number = "relative"
completion-replace = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
skip-levels = 1
character = "│"

[editor.soft-wrap]
enable = true
wrap-indicator = ""

[keys.normal]
"A-," = "goto_previous_buffer"
"A-." = "goto_next_buffer"
A-w = ":buffer-close"
