[[language]]
name = "rust"
language-servers = ["rust-analyzer", "harper"]

[[language]]
name = "markdown"
language-servers = ["mdpls", "harper"]

[language-server.harper]
command = "harper-ls"
args = ["--stdio"]

[language-server.mdpls]
command = "mdpls"
config = { markdown.preview.auto = true, markdown.preview.browser = "zen-browser"}
